
package basesdemipais.Interfaces;

import basesdemipais.propietario;
import basesdemipais.vector;
import java.awt.Color;
import javax.swing.JOptionPane;

public class interfazAgInmueble extends javax.swing.JFrame {

    public static Object apto;
    public static int codigo;
    public static String tipo;
    public static propietario p;
    public static double tamano;
    public static String zona;
    public static String direccion;
    public static double precio;

    /**
     * Creates new form interfazAgInmueble
     */
    public interfazAgInmueble() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbtipoinmueble = new javax.swing.JComboBox<>();
        jtftamano = new javax.swing.JTextField();
        jtfdireccion = new javax.swing.JTextField();
        jcbzona = new javax.swing.JComboBox<>();
        jtfcodigo = new javax.swing.JTextField();
        jbregresar = new javax.swing.JButton();
        jbcontinuar = new javax.swing.JButton();
        jltipoinmueble = new javax.swing.JLabel();
        jlpropietario = new javax.swing.JLabel();
        jltamaño = new javax.swing.JLabel();
        jlzona = new javax.swing.JLabel();
        jlcodigo = new javax.swing.JLabel();
        jldireccion = new javax.swing.JLabel();
        jtfidpropietario = new javax.swing.JTextField();
        jbbuscarpropietario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Inmueble");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jcbtipoinmueble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Apartamento", "Parqueadero", "Local" }));
        jcbtipoinmueble.setEnabled(false);
        jcbtipoinmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbtipoinmuebleActionPerformed(evt);
            }
        });

        jtftamano.setEnabled(false);

        jtfdireccion.setEnabled(false);
        jtfdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfdireccionActionPerformed(evt);
            }
        });

        jcbzona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Sabaneta", "Envigado", "Itagui", "Poblado", "Caldas", "Manrique", "Belen", "Cristorey" }));
        jcbzona.setEnabled(false);
        jcbzona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbzonaActionPerformed(evt);
            }
        });

        jtfcodigo.setEditable(false);
        jtfcodigo.setEnabled(false);

        jbregresar.setText("regresar");
        jbregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbregresarActionPerformed(evt);
            }
        });

        jbcontinuar.setText("Continuar");
        jbcontinuar.setEnabled(false);
        jbcontinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcontinuarActionPerformed(evt);
            }
        });

        jltipoinmueble.setText("Tipo de inmueble");

        jlpropietario.setText("Ingrese ID del Propietario");

        jltamaño.setText("Tamaño de inmueble");

        jlzona.setText("Zona");

        jlcodigo.setText("Codigo (automatico)");

        jldireccion.setText("Dirección");

        jtfidpropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfidpropietarioActionPerformed(evt);
            }
        });

        jbbuscarpropietario.setText("Buscar propietario");
        jbbuscarpropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarpropietarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbregresar)
                    .addComponent(jbcontinuar))
                .addGap(46, 46, 46))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbtipoinmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jltipoinmueble))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlcodigo)))
                    .addComponent(jlpropietario)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jbbuscarpropietario))
                    .addComponent(jtfidpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jldireccion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtftamano, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jltamaño)
                            .addGap(145, 145, 145)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlzona)
                                .addComponent(jcbzona, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jtfdireccion)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlpropietario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfidpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbbuscarpropietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jltipoinmueble)
                    .addComponent(jlcodigo))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtipoinmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jltamaño)
                    .addComponent(jlzona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtftamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbzona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jldireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jbregresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbcontinuar)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbzonaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jcbzonaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jcbzonaActionPerformed

    private void jtfdireccionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfdireccionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfdireccionActionPerformed

    private void jbregresarActionPerformed(java.awt.event.ActionEvent evt) {
        basesdemipais.Interfaces.interfazInicio.getObjInicio().setVisible(true);
        this.setVisible(false);
    }

    private void jbcontinuarActionPerformed(java.awt.event.ActionEvent evt) {

        boolean uwu = true;
        if (jcbtipoinmueble.getSelectedItem().equals("Seleccione")) {
            uwu = false;
            jcbtipoinmueble.setBackground(Color.RED);
        }
        if (jcbzona.getSelectedItem().equals("Seleccione")) {
            uwu = false;
            jcbzona.setBackground(Color.RED);
        }
        if (jtftamano.getText().equals("")) {
            uwu = false;
            jtftamano.setBackground(new java.awt.Color(255, 204, 204));
        }
        if (jtfdireccion.getText().equals("")) {
            uwu = false;
            jtfdireccion.setBackground(new java.awt.Color(255, 204, 204));
        }
        if (jcbzona.getSelectedItem().equals("Selecciona")) {
            uwu = false;
            jcbzona.setBackground(new java.awt.Color(255, 204, 204));
        }
        if (uwu == false) {
            JOptionPane.showMessageDialog(null, "Datos invalidos o faltantes");
        }
        if (uwu == true) {
            if (jcbtipoinmueble.getSelectedIndex() == 1) {
                codigo = Integer.parseInt(jtfcodigo.getText());
                tipo = String.valueOf(jcbtipoinmueble.getSelectedItem());
                p = basesdemipais.Interfaces.interfazInicio.getPropietarios()
                        .Buscar(Integer.parseInt(jtfidpropietario.getText()));
                tamano = Double.parseDouble(jtftamano.getText());
                zona = String.valueOf(jcbzona.getSelectedItem());
                direccion = jtfdireccion.getText();
                precio = vector.defPrecio(zona, tamano, tipo);

                interfazApartamento apto = new interfazApartamento();
                apto.setVisible(true);
                this.setVisible(false);

            } else if (jcbtipoinmueble.getSelectedIndex() == 2) {
                codigo = Integer.parseInt(jtfcodigo.getText());
                tipo = String.valueOf(jcbtipoinmueble.getSelectedItem());
                p = basesdemipais.Interfaces.interfazInicio.getPropietarios()
                        .Buscar(Integer.parseInt(jtfidpropietario.getText()));
                tamano = Double.parseDouble(jtftamano.getText());
                zona = String.valueOf(jcbzona.getSelectedItem());
                direccion = jtfdireccion.getText();
                precio = vector.defPrecio(zona, tamano, tipo);

                interfazParqueadero parqueadero = new interfazParqueadero();
                parqueadero.setVisible(true);
                this.setVisible(false);

            } else if (jcbtipoinmueble.getSelectedIndex() == 3) {
                codigo = Integer.parseInt(jtfcodigo.getText());
                tipo = String.valueOf(jcbtipoinmueble.getSelectedItem());
                p = basesdemipais.Interfaces.interfazInicio.getPropietarios()
                        .Buscar(Integer.parseInt(jtfidpropietario.getText()));
                tamano = Double.parseDouble(jtftamano.getText());
                zona = String.valueOf(jcbzona.getSelectedItem());
                direccion = jtfdireccion.getText();
                precio = vector.defPrecio(zona, tamano, tipo);

                interfazLocal local = new interfazLocal();
                local.setVisible(true);
                this.setVisible(false);
            }
        }
    }// GEN-LAST:event_jbcontinuarActionPerformed

    private void jcbtipoinmuebleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jcbtipoinmuebleActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jcbtipoinmuebleActionPerformed

    private void jtfidpropietarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfidpropietarioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfidpropietarioActionPerformed

    private void jbbuscarpropietarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbbuscarpropietarioActionPerformed
        // TODO add your handling code here:
        if (!jtfidpropietario.getText().equals("")) {

            int id = Integer.parseInt(jtfidpropietario.getText());
            if (basesdemipais.Interfaces.interfazInicio.getPropietarios().Buscar(id) != null) {
                jtfidpropietario.setEnabled(false);
                jtftamano.setEnabled(true);
                jtfdireccion.setEnabled(true);
                jcbtipoinmueble.setEnabled(true);
                jcbzona.setEnabled(true);
                jbcontinuar.setEnabled(true);
                JOptionPane.showMessageDialog(null,
                        basesdemipais.Interfaces.interfazInicio.getPropietarios()
                                .Buscar(Integer.parseInt(jtfidpropietario.getText())));

                // Agregar funcion para asignar codigo automatico
                jtfcodigo.setText(String.valueOf(
                        basesdemipais.Interfaces.interfazInicio.getInmuebles().codigo()));
            } else {
                JOptionPane.showMessageDialog(null, "El usuario no ha sido encontrado, por favor verifique que exista.");
            }

        }
    }// GEN-LAST:event_jbbuscarpropietarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazAgInmueble.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazAgInmueble.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazAgInmueble.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazAgInmueble.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazAgInmueble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbbuscarpropietario;
    private javax.swing.JButton jbcontinuar;
    private javax.swing.JButton jbregresar;
    private javax.swing.JComboBox<String> jcbtipoinmueble;
    private javax.swing.JComboBox<String> jcbzona;
    private javax.swing.JLabel jlcodigo;
    private javax.swing.JLabel jldireccion;
    private javax.swing.JLabel jlpropietario;
    private javax.swing.JLabel jltamaño;
    private javax.swing.JLabel jltipoinmueble;
    private javax.swing.JLabel jlzona;
    private javax.swing.JTextField jtfcodigo;
    private javax.swing.JTextField jtfdireccion;
    private javax.swing.JTextField jtfidpropietario;
    private javax.swing.JTextField jtftamano;
    // End of variables declaration//GEN-END:variables
}
