/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basesdemipais.Interfaces;

import basesdemipais.apartamento;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author celislinux
 */
public class interfazApartamento extends javax.swing.JFrame {

        /**
         * Creates new form interfazApartamento
         */
        public interfazApartamento() {
                initComponents();
                this.setLocationRelativeTo(null);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jltitulo = new javax.swing.JLabel();
        jlnumerodehabitaciones = new javax.swing.JLabel();
        jldesc = new javax.swing.JLabel();
        jldesc2 = new javax.swing.JLabel();
        jtfnumerodehabitaciones = new javax.swing.JTextField();
        jlnumerodearmarios = new javax.swing.JLabel();
        jtfnumerodearmarios = new javax.swing.JTextField();
        jlnumerodebanos = new javax.swing.JLabel();
        jtfnumerodebanos = new javax.swing.JTextField();
        jcbtipodecocina = new javax.swing.JComboBox<>();
        jltipodecocina = new javax.swing.JLabel();
        jltipodepiso = new javax.swing.JLabel();
        jcbtipodepiso = new javax.swing.JComboBox<>();
        jbguardar = new javax.swing.JButton();
        jblimpiar = new javax.swing.JButton();
        jbimagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(653, 463));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jltitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jltitulo.setForeground(new java.awt.Color(255, 255, 255));
        jltitulo.setText("Agregar un apartamento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jltitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jltitulo)
                .addGap(21, 21, 21))
        );

        jlnumerodehabitaciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlnumerodehabitaciones.setForeground(new java.awt.Color(0, 0, 0));
        jlnumerodehabitaciones.setText("Número de habitaciones: ");

        jldesc.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jldesc.setForeground(new java.awt.Color(0, 0, 0));
        jldesc.setText("En esta sección podras agregar un apartamento que estará bajo nuestra responsabilidad.");

        jldesc2.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jldesc2.setForeground(new java.awt.Color(0, 0, 0));
        jldesc2.setText("Los siguientes items son necesarios para agregar un apartamento.");

        jtfnumerodehabitaciones.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jtfnumerodehabitaciones.setForeground(new java.awt.Color(51, 51, 51));
        jtfnumerodehabitaciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfnumerodehabitacionesFocusGained(evt);
            }
        });
        jtfnumerodehabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnumerodehabitacionesActionPerformed(evt);
            }
        });

        jlnumerodearmarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlnumerodearmarios.setForeground(new java.awt.Color(0, 0, 0));
        jlnumerodearmarios.setText("Número de armarios: ");

        jtfnumerodearmarios.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jtfnumerodearmarios.setForeground(new java.awt.Color(51, 51, 51));
        jtfnumerodearmarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfnumerodearmariosFocusGained(evt);
            }
        });
        jtfnumerodearmarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnumerodearmariosActionPerformed(evt);
            }
        });

        jlnumerodebanos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlnumerodebanos.setForeground(new java.awt.Color(0, 0, 0));
        jlnumerodebanos.setText("Número de baños: ");

        jtfnumerodebanos.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jtfnumerodebanos.setForeground(new java.awt.Color(51, 51, 51));
        jtfnumerodebanos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfnumerodebanosFocusGained(evt);
            }
        });
        jtfnumerodebanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnumerodebanosActionPerformed(evt);
            }
        });

        jcbtipodecocina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Cocina en L", "Cocina en U", "Cocina con Isla" }));
        jcbtipodecocina.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcbtipodecocina.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcbtipodecocinaFocusGained(evt);
            }
        });

        jltipodecocina.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jltipodecocina.setForeground(new java.awt.Color(0, 0, 0));
        jltipodecocina.setText("Tipo de cocina: ");

        jltipodepiso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jltipodepiso.setForeground(new java.awt.Color(0, 0, 0));
        jltipodepiso.setText("Tipo de piso: ");

        jcbtipodepiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Piso de madera", "Piso en cerámica", "Piso en baldosas" }));
        jcbtipodepiso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcbtipodepisoFocusGained(evt);
            }
        });

        jbguardar.setText("Guardar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });

        jblimpiar.setText("Limpiar");
        jblimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimpiarActionPerformed(evt);
            }
        });

        jbimagen.setBackground(new java.awt.Color(60, 63, 65));
        jbimagen.setIcon(new javax.swing.ImageIcon("/home/celislinux/NetBeansProjects/BasesDeMiPais/src/main/java/basesdemipais/BASES DE MI PAIS.png")); // NOI18N
        jbimagen.setBorder(null);
        jbimagen.setBorderPainted(false);
        jbimagen.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jldesc2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jltipodecocina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jcbtipodecocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jltipodepiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jcbtipodepiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(97, 97, 97)
                                        .addComponent(jblimpiar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbguardar)
                                        .addGap(0, 10, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlnumerodebanos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfnumerodebanos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlnumerodehabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfnumerodehabitaciones))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlnumerodearmarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfnumerodearmarios, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jldesc)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jldesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jldesc2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jlnumerodehabitaciones)
                        .addGap(6, 6, 6)
                        .addComponent(jtfnumerodehabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlnumerodearmarios)
                        .addGap(2, 2, 2)
                        .addComponent(jtfnumerodearmarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlnumerodebanos)
                        .addGap(2, 2, 2)
                        .addComponent(jtfnumerodebanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jltipodecocina)
                    .addComponent(jltipodepiso))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtipodecocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbtipodepiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbguardar)
                    .addComponent(jblimpiar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void jtfnumerodehabitacionesFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jtfnumerodehabitacionesFocusGained
                // TODO add your handling code here:
                jtfnumerodehabitaciones.setBackground(Color.WHITE);
        }// GEN-LAST:event_jtfnumerodehabitacionesFocusGained

        private void jtfnumerodehabitacionesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfnumerodehabitacionesActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jtfnumerodehabitacionesActionPerformed

        private void jtfnumerodearmariosFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jtfnumerodearmariosFocusGained
                // TODO add your handling code here:
                jtfnumerodearmarios.setBackground(Color.WHITE);
        }// GEN-LAST:event_jtfnumerodearmariosFocusGained

        private void jtfnumerodearmariosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfnumerodearmariosActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jtfnumerodearmariosActionPerformed

        private void jtfnumerodebanosFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jtfnumerodebanosFocusGained
                // TODO add your handling code here:
                jtfnumerodebanos.setBackground(Color.WHITE);
        }// GEN-LAST:event_jtfnumerodebanosFocusGained

        private void jtfnumerodebanosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfnumerodebanosActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jtfnumerodebanosActionPerformed

        private void jcbtipodecocinaFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jcbtipodecocinaFocusGained
                // TODO add your handling code here:
                jcbtipodecocina.setBackground(Color.WHITE);
        }// GEN-LAST:event_jcbtipodecocinaFocusGained

        private void jcbtipodepisoFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jcbtipodepisoFocusGained
                // TODO add your handling code here:
                jcbtipodepiso.setBackground(Color.WHITE);
        }// GEN-LAST:event_jcbtipodepisoFocusGained

        private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbguardarActionPerformed
                // TODO add your handling code here:

                boolean comp = true;
                if (jtfnumerodehabitaciones.getText().equals("")) {
                        comp = false;
                        jtfnumerodehabitaciones.setBackground(new java.awt.Color(255, 204, 204));
                }
                if (jtfnumerodearmarios.getText().equals("")) {
                        comp = false;
                        jtfnumerodearmarios.setBackground(new java.awt.Color(255, 204, 204));
                }
                if (jtfnumerodebanos.getText().equals("")) {
                        comp = false;
                        jtfnumerodebanos.setBackground(new java.awt.Color(255, 204, 204));
                }

                if (jcbtipodecocina.getSelectedItem().equals("Seleccione")) {
                        comp = false;
                        jcbtipodecocina.setBackground(new java.awt.Color(255, 0, 51));
                }

                if (jcbtipodepiso.getSelectedItem().equals("Seleccione")) {
                        comp = false;
                        jcbtipodepiso.setBackground(new java.awt.Color(255, 0, 51));
                }

                if (comp == false) {
                        JOptionPane.showMessageDialog(null, "Datos insuficientes o invalidos");
                }

                if (comp) {
                        int numeroHabitaciones = Integer.parseInt(jtfnumerodehabitaciones.getText());

                        int numeroArmarios = Integer.parseInt(jtfnumerodearmarios.getText());
                        int numeroBanos = Integer.parseInt(jtfnumerodebanos.getText());
                        String tipoCocina = (String) jcbtipodecocina.getSelectedItem();
                        String tipoPiso = (String) jcbtipodepiso.getSelectedItem();
                        // FALTA AGREGAR A VEC///

                        
                        interfazAgInmueble claseprueba = new interfazAgInmueble();
                        apartamento apto = new apartamento(claseprueba.codigo, claseprueba.p, claseprueba.tamano, claseprueba.direccion, claseprueba.zona, claseprueba.precio, numeroHabitaciones, numeroArmarios, numeroBanos,tipoPiso, tipoCocina);
                        
                        if(basesdemipais.Interfaces.interfazInicio.getInmuebles().Adicionar(apto)){
                            JOptionPane.showMessageDialog(null, "Inmueble creado");
                            basesdemipais.Interfaces.interfazInicio.getObjInicio().setVisible(true);
                            this.setVisible(false);
                        }
                        
                        

                }
        }// GEN-LAST:event_jbguardarActionPerformed

        private void jblimpiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jblimpiarActionPerformed
                // TODO add your handling code here:
                jtfnumerodehabitaciones.setText("");
                jtfnumerodehabitaciones.setBackground(Color.WHITE);
                jtfnumerodearmarios.setText("");
                jtfnumerodearmarios.setBackground(Color.WHITE);
                jtfnumerodebanos.setText("");
                jtfnumerodebanos.setBackground(Color.WHITE);
                jcbtipodepiso.setSelectedItem("Seleccione");
                jcbtipodepiso.setBackground(Color.WHITE);
                jcbtipodecocina.setSelectedItem("Seleccione");
                jcbtipodecocina.setBackground(Color.WHITE);
        }// GEN-LAST:event_jblimpiarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(interfazApartamento.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(interfazApartamento.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(interfazApartamento.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(interfazApartamento.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new interfazApartamento().setVisible(true);
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbimagen;
    private javax.swing.JButton jblimpiar;
    private javax.swing.JComboBox<String> jcbtipodecocina;
    private javax.swing.JComboBox<String> jcbtipodepiso;
    private javax.swing.JLabel jldesc;
    private javax.swing.JLabel jldesc2;
    private javax.swing.JLabel jlnumerodearmarios;
    private javax.swing.JLabel jlnumerodebanos;
    private javax.swing.JLabel jlnumerodehabitaciones;
    private javax.swing.JLabel jltipodecocina;
    private javax.swing.JLabel jltipodepiso;
    private javax.swing.JLabel jltitulo;
    private javax.swing.JTextField jtfnumerodearmarios;
    private javax.swing.JTextField jtfnumerodebanos;
    private javax.swing.JTextField jtfnumerodehabitaciones;
    // End of variables declaration//GEN-END:variables
        public static String Mostrar(String[] vector) {
                if (vector == null || vector.length == 0) {
                        return ""; // Devuelve una cadena vacía si el vector es nulo o está vacío.
                }

                StringBuilder resultado = new StringBuilder();

                for (String elemento : vector) {
                        resultado.append(elemento);
                        resultado.append(" "); // Agregamos un espacio entre cada elemento
                }

                return resultado.toString();
        }

}
